### ISSUE TITLE
Windows build - missed libgcc_s_dw2-1.dll

### ISSUE THREAD

**Issue by sergey-shambir** [dkfans/png2ico#1]
Windows build requires parts of g++ runtime (libgcc_s_dw2-1.dll) which isn't included in distribution:
![default](https://user-images.githubusercontent.com/1856842/35974725-4746a310-0ceb-11e8-9ff6-78e3dae4f93c.png)

**Comment by mefistotelis** [comment]
I don't think I provided any builds of the tool, or did I?

png2ico has no direct dependency on any libgcc library. These are added by the linker, if you're using gcc.

If you're building it with your GCC, it is up to you to either provide the libraries from your toolchain, or set a linker flag which uses static versions of libraries and compiles them into the artifact (-static).

**Comment by sergey-shambir** [comment]
Here are builds https://github.com/dkfans/png2ico/releases
Anyway, I've already compiled it with MSVC for my needs, thanks

**Comment by mefistotelis** [comment]
Thanks for the link; I completely forgot about these.

Anyway, closed.
